services:
  - type: web
    name: subash-portfolio-api
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: ALLOWED_ORIGINS
        value: https://subash-portfolio.onrender.com

  - type: web
    name: subash-portfolio
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run render:build
    staticPublishPath: dist/subash-portfolio/browser
    envVars:
      - key: API_URL
        value: https://subash-portfolio-api.onrender.com